### ISSUE TITLE
KeyNotFound: key 'Dolphin Packages' not found in RPackageOrganizer

### ISSUE THREAD

**Issue by fxgallego** [rko281/DolphinToPharo#1]
Just installed DolphinToPharo and the first time I try to import a package "Dolphin Packages" doesn't exists yet.
After adding it from the SystemBrowser works OK.

![image](https://user-images.githubusercontent.com/2080171/106747867-34b2cc00-6603-11eb-9b9b-2cd1dd53c7e5.png)

**Comment by fxgallego** [comment]
I changed `dolphinPackages` as:
```smalltalk
dolphinPackages

	"This actual package"

	^self organizer packageNamed: 'Dolphin Packages' ifAbsent: [ self organizer createPackageNamed: 'Dolphin Packages' ]
```
There is a `checkPackageExistsOrRegister: ` method but it doesn't returns the package...

**Comment by rko281** [comment]
The issue is down to the main package changing name from 'Dolphin Packages' to 'Dolphin to Pharo'. I did update this method at some point but the change looks to have got lost. I'll fix it.
